config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :categories, except: %i[update destroy] do
    resources :purchases, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_purchase.rb
class CategoriesPurchase < ApplicationRecord
  belongs_to :category
  belongs_to :purchase
end

app/models/category.rb
# class Category < ApplicationRecord
#   belongs_to :author, class_name: 'User'
#   has_many :categories_purchases, dependent: :destroy, class_name: 'CategoriesPurchases'
#   has_many :purchases, through: :categories_purchases, dependent: :destroy

#   validates :name, :icon, presence: true
# end

# category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
    has_many :categories_purchases
  has_many :purchases, through: :categories_purchases
end

app/models/purchase.rb
# class Purchase < ApplicationRecord
#   belongs_to :author, class_name: 'User'
#   has_many :categories_purchases, dependent: :destroy, class_name: 'CategoriesPurchases'
#   has_many :categories, through: :categories_purchases, dependent: :destroy

#   validates :name, presence: true
#   validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
# end

# purchase.rb
# class Purchase < ApplicationRecord
#   has_many :categories_purchases, foreign_key: 'author_id'
#   has_many :categories, through: :categories_purchases
# end


class Purchase < ApplicationRecord
  has_many :categories_purchases, foreign_key: 'purchase_id'
  has_many :categories, through: :categories_purchases
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy, foreign_key: :author_id
  has_many :purchases, dependent: :destroy, foreign_key: :author_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(author_id: current_user.id).includes([:author]).order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.where(author_id: current_user.id, id: params[:id]).includes([:author])[0]
    @purchases = @category.purchases.order(created_at: :desc)
  end

  def create
    @category = Category.new(category_params)
    @category.author = current_user
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created!'
    else
      render :new, status: 422, notice: 'An error occurred'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless current_user

    redirect_to '/categories'
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def new
    @purchase = Purchase.new
    @categories = Category.where(author_id: current_user.id).order(created_at: :desc)
    @selected_category = Category.find(params[:category_id])
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.author_id = current_user.id  # Use author_id instead of author

    if @purchase.save
      params[:category_ids].each do |id|
        CategoriesPurchase.create(category_id: id.to_i, purchase_id: @purchase.id)  # Corrected class name
      end
      redirect_to category_path(params[:category_id]), notice: 'Transaction added successfully'
    else
      @categories = Category.where(author_id: current_user.id).order(created_at: :desc)
      render :new, status: :unprocessable_entity  # Use symbol instead of status code
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="page-div">


  <section class="page-header-section">
    <div class="page-header">
      <div class="bars"><i class="fa-solid fa-bars"></i></div>
      <div class="heading">CATEGORIES</div>
      <div class="search"><i class="fa-solid fa-magnifying-glass"></i></div>
    </div>

    <% if user_signed_in? %>
      <div class="sign-out-btn"> <%= button_to "Log out", '/users/sign_out', method: :delete %> </div>
    <%end%>
  </section>

  <% if @categories.length.positive? %>
    <div class="page-mid-section">
      <% @categories.each do |category| %>
        <%= link_to "/categories/#{category.id}" do %>
          <div class="cat-item">
            <div class="cat-img-box">
              <img class="cat-img" src=<%= category.icon %> alt=<%= category.name %> >
            </div>
            <div class="cat-info">
              <p class="cat-name"><%= category.name.capitalize %> <p>
              <small class="cat-date"><%= category.created_at.strftime('%d-%b-%Y') %></small>
            </div>
            <div class="cat-sum">
              <p>$<%= category.purchases.sum('amount') %> <p>
            </div>
          </div>
        <%end%>
      <% end %>
    </div>
  <% else %>
    <p>No Categories created.</p>
  <% end %>

  <div class="add-container">
    <button><%= link_to 'ADD NEW CATEGORY', new_category_path %></button>
  </div>

</div>

app/views/categories/new.html.erb
<div class="page-div">

  <section class="page-header-section">
    <div class="page-header">
      <div class="back">
        <%= link_to categories_path do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="heading">NEW CATEGORY</div>
      <div></div>
    </div>
  </section>

  <div class="page-mid-section">
    <% if @category.errors.any? %>
      <div>
        <p><%= pluralize(@category.errors.count, "error") %> found:</p>

        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @category, url: categories_path,  method: :post do | form |%>
    <div>

      <div class="session-field">  
        <%= form.text_field :name, placeholder: 'Name', required: true, class: "session-field-input" %>
      </div>

      <div class="session-field">
        <%= form.text_field :icon, placeholder: 'icon URL', required: true, class: "session-field-input" %>
      </div>

      <div class="save-btn"><%= form.submit 'Save'%></div>
    </div>
    <% end %>
  </div>

</div>

app/views/categories/show.html.erb
<div class="page-div">

  <section class="page-header-section">
    <div class="page-header">
      <div class="back">
        <%= link_to categories_path(@category.id) do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="heading">DETAILS</div>
      <div></div>
    </div>

    <p class="detail-header"><%= @category.name %>: $<%= @category.purchases.sum('amount')%></p>
  </section>

  
  <% if @purchases.length.positive? %>
    <div class="page-mid-section">
      <% @purchases.each do |item| %>
        <div>
          <div class="cat-item">
            <div class="cat-info">
              <p class="cat-name"><%= item.name.capitalize %> <p>
              <small class="cat-date"><%= item.created_at.strftime('%d-%b-%Y') %></small>
            </div>
            <div class="cat-sum">
              <p>$<%= item.amount %><p>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  <% else %>
    <p>No Transactions recorded.</p>
  <% end %>

  <div class="add-container">
    <button><%= link_to 'Add New Transaction', new_category_purchase_path(@category.id) %></button>
  </div>

</div>

app/views/home/index.html.erb
<div class="splash__container">
  <div class="splash__title"><h3>MyBudget</h3></div>
  <div class="splash__session-btns">
    <%= link_to "LOG IN", new_user_session_path %>
    <%= link_to "SIGN UP", new_user_registration_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/purchases/new.html.erb
<div class="page-div">

  <section class="page-header-section">
    <div class="page-header">
      <div class="back">
        <%= link_to categories_path do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      </div>
      <div class="heading">NEW TRANSACTION</div>
      <div></div>
    </div>
    <p class="detail-header">( for: <%= @selected_category.name %> )</p>
  </section>

  <div class="page-mid-section">
  
    <% if @purchase.errors.any? %>
      <div>
        <p><%= pluralize(@purchase.errors.count, "error") %> found:</p>

        <ul>
          <% @purchase.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @purchase, url: category_purchases_path,  method: :post do | form |%>
      <div>
        <div class="session-field">
          <%= form.text_field :name, placeholder: 'Name', required: true, class: "session-field-input" %>
        </div>

        <div class="session-field">
          <%= form.number_field :amount, placeholder: 'Amount', required: true, class: "session-field-input" %> <br />
        </div>

        <p class="trans-p">Select Categories to add this transaction to:</p>
        <div class="trans-checks">
          <% @categories.each do |category| %>
            <% if category.id == @selected_category.id %>
              <%= hidden_field_tag 'category_ids[]', category.id %>
              <%= check_box_tag 'category_ids[]', category.id, true, disabled: true %>
            <% else %>
              <%= check_box_tag 'category_ids[]', category.id %>
            <% end %>
            <%= category.name %><br>
          <% end %>
        </div>

        <button class="save-btn"><%= form.submit "Save Transaction"%></button>
      </div>
    <% end %>
  </div>
</div>